import type { ThemeConfig } from "antd";

export const themeConfig: ThemeConfig = {
  token: {
    colorPrimary: "#1E3A8A",
    colorSuccess: "#22C55E",
    colorWarning: "#FBBF24",
    colorError: "#EF4444",
    colorInfo: "#FBBF24",
    colorBgLayout: "#F8FAFC",
    colorBgContainer: "#FFFFFF",
    colorBgElevated: "#FFFFFF",
    colorBgSpotlight: "#F1F5F9",
    colorBorder: "#E2E8F0",
    colorBorderSecondary: "#F1F5F9",
    colorText: "#0F172A",
    colorTextSecondary: "#475569",
    colorTextTertiary: "#64748B",
    colorTextQuaternary: "#94A3B8",
    colorBgTextHover: "rgba(30, 58, 138, 0.05)",
    colorPrimaryBg: "rgba(30, 58, 138, 0.06)",
    colorPrimaryHover: "#1E40AF",
    colorPrimaryActive: "#172554",
    borderRadius: 12,
    borderRadiusLG: 16,
    borderRadiusSM: 8,
    controlHeight: 42,
    controlHeightLG: 50,
    controlHeightSM: 34,
    fontSize: 14,
    fontSizeLG: 16,
    fontSizeHeading1: 36,
    fontSizeHeading2: 28,
    fontSizeHeading3: 22,
    fontSizeHeading4: 18,
    fontSizeHeading5: 15,
    fontFamily: "'Inter', ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
    fontFamilyCode: "'JetBrains Mono', 'Fira Code', monospace",
    lineHeight: 1.6,
    lineHeightHeading1: 1.25,
    lineHeightHeading2: 1.3,
    lineHeightHeading3: 1.35,
    boxShadow: "0 1px 2px 0 rgba(0, 0, 0, 0.03), 0 1px 6px -1px rgba(0, 0, 0, 0.02)",
    boxShadowSecondary: "0 4px 16px 0 rgba(0, 0, 0, 0.06), 0 2px 4px -2px rgba(0, 0, 0, 0.03)",
    boxShadowTertiary: "0 12px 40px 0 rgba(0, 0, 0, 0.08)",
    motionDurationFast: "0.15s",
    motionDurationMid: "0.25s",
    motionDurationSlow: "0.35s",
    motionEaseInOut: "cubic-bezier(0.4, 0, 0.2, 1)",
    motionEaseOut: "cubic-bezier(0, 0, 0.2, 1)",
    paddingXXS: 4,
    paddingXS: 8,
    paddingSM: 12,
    padding: 16,
    paddingMD: 20,
    paddingLG: 24,
    paddingXL: 32,
    marginXXS: 4,
    marginXS: 8,
    marginSM: 12,
    margin: 16,
    marginMD: 20,
    marginLG: 24,
    marginXL: 32,
    marginXXL: 48,
  },
  components: {
    Button: {
      colorPrimary: "#1E3A8A",
      primaryColor: "#FFFFFF",
      colorPrimaryHover: "#1E40AF",
      colorPrimaryActive: "#172554",
      borderRadius: 10,
      borderRadiusLG: 12,
      borderRadiusSM: 8,
      controlHeight: 42,
      controlHeightLG: 50,
      controlHeightSM: 34,
      fontWeight: 600,
      fontSize: 14,
      fontSizeLG: 15,
      fontSizeSM: 13,
      defaultBg: "#FFFFFF",
      defaultColor: "#0F172A",
      defaultBorderColor: "#E2E8F0",
      defaultHoverBg: "#F8FAFC",
      defaultHoverColor: "#1E3A8A",
      defaultHoverBorderColor: "#1E3A8A",
      primaryShadow: "0 1px 3px rgba(30, 58, 138, 0.15)",
      defaultShadow: "0 1px 2px rgba(0, 0, 0, 0.03)",
      paddingContentHorizontal: 20,
      paddingContentHorizontalLG: 28,
      paddingContentHorizontalSM: 14,
    },
    Menu: {
      itemBg: "transparent",
      itemSelectedBg: "rgba(30, 58, 138, 0.07)",
      itemSelectedColor: "#1E3A8A",
      itemColor: "#475569",
      itemHoverColor: "#1E3A8A",
      itemHoverBg: "rgba(30, 58, 138, 0.04)",
      colorPrimary: "#1E3A8A",
      borderRadius: 10,
      itemMarginInline: 8,
      itemHeight: 44,
      fontSize: 14,
      subMenuItemBg: "transparent",
      groupTitleColor: "#94A3B8",
      groupTitleFontSize: 11,
      paddingXS: 16,
    },
    Layout: {
      bodyBg: "#F8FAFC",
      headerBg: "#FFFFFF",
      siderBg: "#FFFFFF",
      headerHeight: 64,
      triggerBg: "#F1F5F9",
      triggerColor: "#64748B",
      fontSize: 14,
    },
    Card: {
      colorBgContainer: "#FFFFFF",
      colorBorderSecondary: "#F1F5F9",
      paddingLG: 24,
      paddingMD: 20,
      paddingSM: 14,
      borderRadiusLG: 14,
      borderRadiusSM: 10,
      fontSize: 14,
    },
    Table: {
      headerBg: "#F8FAFC",
      headerColor: "#64748B",
      headerBorderRadius: 10,
      rowHoverBg: "rgba(30, 58, 138, 0.02)",
      borderColor: "#F1F5F9",
      fontSize: 14,
    },
    Tag: {
      defaultBg: "#F8FAFC",
      defaultColor: "#475569",
      borderRadius: 6,
      fontSizeSM: 12,
      lineHeightSM: 1.5,
    },
    Tabs: {
      inkBarColor: "#1E3A8A",
      itemSelectedColor: "#1E3A8A",
      itemColor: "#64748B",
      itemHoverColor: "#1E3A8A",
      fontSize: 14,
      titleFontSize: 14,
    },
    Modal: {
      headerBg: "#FFFFFF",
      contentBg: "#FFFFFF",
      footerBg: "#FFFFFF",
      borderRadiusLG: 16,
      paddingMD: 24,
      paddingContentHorizontal: 24,
      paddingContentVertical: 20,
    },
    Drawer: {
      colorBgElevated: "#FFFFFF",
      borderRadiusLG: 16,
    },
    Select: {
      colorPrimary: "#1E3A8A",
      optionSelectedBg: "rgba(30, 58, 138, 0.08)",
      optionSelectedColor: "#1E3A8A",
      optionActiveBg: "#F8FAFC",
      colorBgElevated: "#FFFFFF",
      borderRadius: 10,
      controlHeight: 42,
      controlHeightLG: 50,
      controlHeightSM: 34,
    },
    Input: {
      colorPrimary: "#1E3A8A",
      activeBorderColor: "#1E3A8A",
      hoverBorderColor: "#1E40AF",
      colorBgContainer: "#FFFFFF",
      colorBorder: "#E2E8F0",
      borderRadius: 10,
      controlHeight: 42,
      controlHeightLG: 50,
      controlHeightSM: 34,
      paddingBlock: 10,
      paddingInline: 14,
      activeShadow: "0 0 0 3px rgba(30, 58, 138, 0.08)",
    },
    InputNumber: {
      colorPrimary: "#1E3A8A",
      activeBorderColor: "#1E3A8A",
      hoverBorderColor: "#1E40AF",
      colorBgContainer: "#FFFFFF",
      colorBorder: "#E2E8F0",
      borderRadius: 10,
      controlHeight: 42,
      activeShadow: "0 0 0 3px rgba(30, 58, 138, 0.08)",
    },
    Form: {
      labelColor: "#0F172A",
      labelFontSize: 13,
      labelHeight: 22,
      itemMarginBottom: 22,
    },
    Descriptions: {
      labelColor: "#64748B",
      contentColor: "#0F172A",
      borderRadiusLG: 12,
    },
    Statistic: {
      contentFontSize: 28,
      titleFontSize: 13,
    },
    Divider: {
      colorSplit: "#E2E8F0",
      marginLG: 24,
    },
    List: {
      headerBg: "transparent",
      footerBg: "transparent",
    },
    Progress: {
      defaultColor: "#1E3A8A",
      remainingColor: "#F1F5F9",
      borderRadius: 4,
    },
    Notification: {
      colorBgElevated: "#FFFFFF",
      borderRadiusLG: 14,
      paddingMD: 20,
      paddingContentHorizontal: 20,
    },
    Tooltip: {
      colorBgSpotlight: "#0F172A",
      borderRadius: 8,
      controlHeight: 32,
      fontSize: 13,
    },
    Popover: {
      colorBgElevated: "#FFFFFF",
      borderRadiusLG: 12,
    },
    Steps: { colorPrimary: "#1E3A8A" },
    Switch: { colorPrimary: "#1E3A8A" },
    Radio: { colorPrimary: "#1E3A8A" },
    Checkbox: { colorPrimary: "#1E3A8A" },
    Slider: { colorPrimary: "#1E3A8A" },
    Spin: { colorPrimary: "#1E3A8A" },
    Badge: {
      colorPrimary: "#1E3A8A",
      fontSize: 11,
    },
    Alert: {
      borderRadiusLG: 12,
      withDescriptionPadding: 16,
    },
    Skeleton: {
      gradientFromColor: "#F1F5F9",
      borderRadius: 8,
    },
    Dropdown: {
      colorBgElevated: "#FFFFFF",
      borderRadiusLG: 12,
    },
    DatePicker: {
      colorPrimary: "#1E3A8A",
      activeBorderColor: "#1E3A8A",
      hoverBorderColor: "#1E40AF",
      colorBgContainer: "#FFFFFF",
      colorBorder: "#E2E8F0",
      borderRadius: 10,
      controlHeight: 42,
    },
    Breadcrumb: {
      fontSize: 13,
      lastItemColor: "#0F172A",
      linkColor: "#64748B",
      separatorColor: "#CBD5E1",
    },
    Collapse: {
      colorBgContainer: "#FFFFFF",
      colorBorder: "#E2E8F0",
      borderRadiusLG: 12,
    },
    Rate: {
      colorFill: "#FBBF24",
    },
    Segmented: {
      colorBgLayout: "#F1F5F9",
      borderRadius: 10,
      trackBg: "#F1F5F9",
      itemSelectedBg: "#FFFFFF",
    },
    Upload: {
      colorBgContainer: "#F8FAFC",
      borderRadiusLG: 12,
    },
  },
};
